#!/usr/bin/env python2
# -*- coding: utf-8 -*-

# tmccli
# ======
# Copyright © 2014 Juhani Imberg
# Released under the MIT License, see LICENSE for details

import lib.tmc as tmc

if __name__ == "__main__":
    tmc.main()